In [1]:
import pandas as pd
from time import time
offers=pd.read_csv('offers.csv')
out=offers[(offers.category>9000)  & (offers.category>9000)]

In [2]:
trainHistory=pd.read_csv('testHistory.csv')
print trainHistory[trainHistory.id == 242209515]

print len(trainHistory)

Empty DataFrame
Columns: [id, chain, offer, market, offerdate]
Index: []
151484

In [3]:
offer_train=pd.merge(offers,trainHistory, on='offer')
print offer_train.iloc[0]

offer            1190530
category            9115
quantity               1
company        108500080
offervalue             5
brand              93904
id              15073302
chain                 15
market                 9
offerdate     2013-05-09
Name: 0, dtype: object

In [4]:
from time import time
t0=time()
train_transaction_category=pd.read_csv('transactions_match_category_test.csv')
train_transaction_category.set_index(['category','date'])
t1=time()
print 'total time='+str(t1-t0)
#print transaction_category

total time=23.7153401375

In [5]:
train_transaction_company=pd.read_csv('transactions_match_company_test.csv')
train_transaction_company.set_index(['company','date'])
#print transaction

                               id  chain  dept  category  brand  productsize  \
company    date
105100050  2012-03-02       86246    205    21      2106  27873        64.00
103700030  2012-03-02       86246    205    26      2630  14647        56.00
           2012-03-06       86246    205    26      2634   3293         6.00
105100050  2012-03-06       86246    205    37      3703   2820        10.75
           2012-03-06       86246    205    41      4109   2820        11.00
           2012-03-07       86246    205    29      2903  72482        15.00
103320030  2012-03-09       86246    205    27      2710    875        14.00
103700030  2012-03-09       86246    205    26      2613  10861        27.00
108500080  2012-03-10       86246    205    64      6406    673         0.75
103700030  2012-03-11       86246    205    26      2630  14647        56.00
105450050  2012-03-11       86246    205    58      5812   1322        16.00
107127979  2012-03-17       86246    205    99      9909   6732         7.00
104460040  2012-03-17       86246    205    18      1835   9709         3.30
103700030  2012-03-19       86246    205    35      3504   4628        19.00
108500080  2012-03-19       86246    205    64      6408   6967         0.75
105100050  2012-03-21       86246    205    41      4109   2820        11.00
107127979  2012-03-21       86246    205    99      9909   6732        10.00
105450050  2012-03-21       86246    205    58      5812   1322        16.00
108500080  2012-03-24       86246    205    64      6408   6967         0.75
104460040  2012-03-24       86246    205    22      2201   3718        96.00
107127979  2012-03-25       86246    205    99      9909   6732         9.80
105100050  2012-03-25       86246    205    37      3706   2820        10.75
103700030  2012-03-30       86246    205    33      3312  14494         6.38
108500080  2012-03-30       86246    205    64      6409   1949         0.75
104127141  2012-03-30       86246    205    25      2506  26189        16.00
106414464  2012-03-31       86246    205    29      2903   3342        15.00
103320030  2012-03-31       86246    205    35      3509    875        50.00
103700030  2012-03-31       86246    205    33      3312  14494         6.38
           2012-04-01       86246    205    69      6901  16139         2.60
104127141  2012-04-02       86246    205    25      2506  26189        16.00
...                           ...    ...   ...       ...    ...          ...
105100050  2013-07-22  4847628950    166    37      3705   2820        18.80
           2013-07-22  4847628950    166    37      3703   2820        10.75
103700030  2013-07-22  4847628950    166    71      7106   8047        14.20
105190050  2013-07-22  4847628950    166    58      5823  26456         9.00
103700030  2013-07-22  4847628950    166    26      2628   2248         8.00
1076211171 2013-07-22  4847628950    166     7       709  17286         4.20
1089520383 2013-07-22  4847628950    166    99      9909  28840         5.00
103700030  2013-07-22  4847628950    166    35      3504   4628        20.00
105190050  2013-07-22  4847628950    166    58      5823  26456        16.00
105100050  2013-07-22  4847628950    166    37      3705   2820        19.00
103320030  2013-07-22  4847628950    166    72      7205    305         6.00
103700030  2013-07-22  4847628950    166    26      2634   3293        30.00
104460040  2013-07-22  4847628950    166    22      2201   3718       121.00
108079383  2013-07-22  4847628950    166    21      2118   6926        16.90
104610040  2013-07-23  4847628950    166    56      5620  15889         8.00
1076211171 2013-07-23  4847628950    166     7       703  17286         3.44
104460040  2013-07-23  4847628950    166    27      2710   6743         7.00
105100050  2013-07-23  4847628950    166    37      3703   2820        10.75
1089520383 2013-07-23  4847628950    166    99      9909  28840         5.00
108500080  2013-07-23  4847628950    166    64      6408  21942         0.75
105190050  2013-07-23  4847628950    166    58      5823  26456         9.00
           2013-07-23  4847628950    166    58      5823  26456         7.50
108500080  2013-07-23  4847628950    166    64      6408  13918         5.00
103700030  2013-07-23  4847628950    166    22      2210   5174        51.00
108079383  2013-07-23  4847628950    166    21      2118   6926        16.90
104460040  2013-07-21  4847787712     46    22      2207   3718        66.00
105100050  2013-07-21  4847787712     46    37      3703   2820        10.50
103320030  2013-07-21  4847787712     46    35      3509    875        75.00
105100050  2013-07-20  4853460972    214    20      2002  27873        33.60
           2013-07-21  4853460972    214    20      2002  27873        33.60

                      productmeasure  purchasequantity  purchaseamount
company    date
105100050  2012-03-02             OZ                 1            3.29
103700030  2012-03-02             CT                 1            1.00
           2012-03-06             RL                 1            4.99
105100050  2012-03-06             OZ                 1            0.79
           2012-03-06             OZ                 2            1.18
           2012-03-07             OZ                 1            0.99
103320030  2012-03-09             LB                 1            6.99
103700030  2012-03-09             CT                 1            8.99
108500080  2012-03-10             LT                 4           27.96
103700030  2012-03-11             CT                 2            2.00
105450050  2012-03-11             OZ                 1            3.79
107127979  2012-03-17             OZ                 2            8.38
104460040  2012-03-17             LB                 1            4.59
103700030  2012-03-19             OZ                 1            1.99
108500080  2012-03-19             LT                 1            3.99
105100050  2012-03-21             OZ                 4            2.36
107127979  2012-03-21             OZ                 1            3.69
105450050  2012-03-21             OZ                 1            5.29
108500080  2012-03-24             LT                 1            3.99
104460040  2012-03-24             OZ                 2            5.58
107127979  2012-03-25             OZ                 1            3.99
105100050  2012-03-25             OZ                 1            1.79
103700030  2012-03-30             OZ                 1            1.99
108500080  2012-03-30             LT                 1            5.59
104127141  2012-03-30             OZ                 1            2.29
106414464  2012-03-31             OZ                 5            5.00
103320030  2012-03-31             OZ                 1            5.89
103700030  2012-03-31             OZ                 1            1.99
           2012-04-01             OZ                 1            2.99
104127141  2012-04-02             OZ                 1            2.29
...                              ...               ...             ...
105100050  2013-07-22             OZ                 1            2.39
           2013-07-22             OZ                 3            5.37
103700030  2013-07-22             OZ                 1            4.99
105190050  2013-07-22             OZ                 3            7.50
103700030  2013-07-22             RL                 1           10.69
1076211171 2013-07-22             OZ                 3           20.97
1089520383 2013-07-22             OZ                 1            3.99
103700030  2013-07-22             OZ                 1            3.79
105190050  2013-07-22             OZ                 1            4.49
105100050  2013-07-22             OZ                 1            2.39
103320030  2013-07-22             OZ                 1            1.19
103700030  2013-07-22             RL                 1           19.99
104460040  2013-07-22             OZ                 4           16.76
108079383  2013-07-22             OZ                 2            3.18
104610040  2013-07-23             OZ                 1            4.19
1076211171 2013-07-23             OZ                 1            5.95
104460040  2013-07-23             LB                 1            3.69
105100050  2013-07-23             OZ                 1            1.59
1089520383 2013-07-23             OZ                 1            3.99
108500080  2013-07-23             LT                 1            5.99
105190050  2013-07-23             OZ                 2            5.00
           2013-07-23             OZ                 1            2.50
108500080  2013-07-23             LT                 1           15.99
103700030  2013-07-23             OZ                 1            6.79
108079383  2013-07-23             OZ                 1            1.59
104460040  2013-07-21             OZ                 1            9.99
105100050  2013-07-21             OZ                 1            1.66
103320030  2013-07-21             OZ                 2            6.98
105100050  2013-07-20             OZ                 1            2.98
           2013-07-21             OZ                 1            2.98

[15793953 rows x 9 columns]

In [6]:
train_transaction_brand=pd.read_csv('transactions_match_brand_test.csv')
train_transaction_brand.set_index(['brand','date'])
#print transaction

                          id  chain  dept  category     company  productsize  \
brand date
13791 2012-03-02       86246    205     9       907   101410010        24.00
5072  2012-03-06       86246    205    10      1013   103890030        17.20
875   2012-03-09       86246    205    27      2710   103320030        14.00
13791 2012-03-10       86246    205     9       907   101410010        13.00
      2012-03-11       86246    205     9       907   101410010        13.00
1322  2012-03-11       86246    205    58      5812   105450050        16.00
6732  2012-03-17       86246    205    99      9909   107127979         7.00
5072  2012-03-18       86246    205    99      9909   107143070        22.00
      2012-03-21       86246    205    99      9909   107143070        22.00
6732  2012-03-21       86246    205    99      9909   107127979        10.00
1322  2012-03-21       86246    205    58      5812   105450050        16.00
13791 2012-03-23       86246    205     9       912   101410010        21.00
3718  2012-03-24       86246    205    22      2201   104460040        96.00
6732  2012-03-25       86246    205    99      9909   107127979         9.80
26189 2012-03-30       86246    205    25      2506   104127141        16.00
875   2012-03-31       86246    205    35      3509   103320030        50.00
13791 2012-04-01       86246    205     9       907   101410010        24.00
26189 2012-04-02       86246    205    25      2506   104127141        16.00
6732  2012-04-04       86246    205    99      9909   107127979         7.00
875   2012-04-04       86246    205    27      2710   103320030        14.00
26189 2012-04-05       86246    205    25      2506   104127141        16.00
13474 2012-04-07       86246    205    32      3203   106414464         5.00
6732  2012-04-14       86246    205    99      9909   107127979        10.00
875   2012-04-16       86246    205    35      3509   103320030        50.00
13791 2012-04-24       86246    205     9       907   101410010        24.00
875   2012-04-29       86246    205    35      3509   103320030        50.00
13791 2012-04-30       86246    205    44      4404   105100050        11.25
      2012-05-03       86246    205     9       907   101410010         9.00
5072  2012-05-04       86246    205    99      9904   107143070        16.00
15889 2012-05-09       86246    205    56      5620   104610040         8.00
...                      ...    ...   ...       ...         ...          ...
      2013-07-21  4847628950    166    56      5616   104610040         7.60
5072  2013-07-21  4847628950    166    99      9909   107143070         9.00
      2013-07-21  4847628950    166    99      9909   107143070        11.00
4294  2013-07-21  4847628950    166    72      7205   103700030         6.40
17286 2013-07-22  4847628950    166     7       703  1076211171         3.68
26456 2013-07-22  4847628950    166    58      5823   105190050        10.00
17286 2013-07-22  4847628950    166     7       706   101200010        15.00
26456 2013-07-22  4847628950    166    58      5823   105190050         9.00
5072  2013-07-22  4847628950    166    99      9909   107143070         9.00
      2013-07-22  4847628950    166    99      9909   107143070         9.90
17286 2013-07-22  4847628950    166     7       709  1076211171         4.20
28840 2013-07-22  4847628950    166    99      9909  1089520383         5.00
26456 2013-07-22  4847628950    166    58      5823   105190050        16.00
5072  2013-07-22  4847628950    166    63      6311   104850040        59.00
3718  2013-07-22  4847628950    166    22      2201   104460040       121.00
6926  2013-07-22  4847628950    166    21      2118   108079383        16.90
15889 2013-07-23  4847628950    166    56      5620   104610040         8.00
5072  2013-07-23  4847628950    166    99      9904  1064312666         1.00
17286 2013-07-23  4847628950    166     7       703  1076211171         3.44
5072  2013-07-23  4847628950    166    99      9909   107143070         8.00
      2013-07-23  4847628950    166    99      9909   107143070         5.00
      2013-07-23  4847628950    166    99      9909   107143070         9.00
      2013-07-23  4847628950    166    99      9909   107143070        12.00
28840 2013-07-23  4847628950    166    99      9909  1089520383         5.00
26456 2013-07-23  4847628950    166    58      5823   105190050         9.00
      2013-07-23  4847628950    166    58      5823   105190050         7.50
5072  2013-07-23  4847628950    166    63      6311   104850040        59.00
6926  2013-07-23  4847628950    166    21      2118   108079383        16.90
3718  2013-07-21  4847787712     46    22      2207   104460040        66.00
875   2013-07-21  4847787712     46    35      3509   103320030        75.00

                 productmeasure  purchasequantity  purchaseamount
brand date
13791 2012-03-02             OZ                 1            3.99
5072  2012-03-06             OZ                 1            3.29
875   2012-03-09             LB                 1            6.99
13791 2012-03-10             OZ                 1            3.49
      2012-03-11             OZ                 1            3.49
1322  2012-03-11             OZ                 1            3.79
6732  2012-03-17             OZ                 2            8.38
5072  2012-03-18             OZ                 1            2.59
      2012-03-21             OZ                 1            2.59
6732  2012-03-21             OZ                 1            3.69
1322  2012-03-21             OZ                 1            5.29
13791 2012-03-23             OZ                 1            4.49
3718  2012-03-24             OZ                 2            5.58
6732  2012-03-25             OZ                 1            3.99
26189 2012-03-30             OZ                 1            2.29
875   2012-03-31             OZ                 1            5.89
13791 2012-04-01             OZ                 2            7.98
26189 2012-04-02             OZ                 1            2.29
6732  2012-04-04             OZ                 1            4.19
875   2012-04-04             LB                 1            6.99
26189 2012-04-05             OZ                 2            4.58
13474 2012-04-07             OZ                 1            3.69
6732  2012-04-14             OZ                 1            3.69
875   2012-04-16             OZ                 1            5.89
13791 2012-04-24             OZ                 1            3.99
875   2012-04-29             OZ                 2           11.78
13791 2012-04-30             OZ                 1            3.09
      2012-05-03             OZ                 1            3.49
5072  2012-05-04             OZ                 3            4.14
15889 2012-05-09             OZ                 2            9.38
...                         ...               ...             ...
      2013-07-21             OZ                 1            3.99
5072  2013-07-21             OZ                 3            4.50
      2013-07-21             OZ                 2            7.98
4294  2013-07-21             OZ                 1            1.49
17286 2013-07-22             OZ                 1            5.95
26456 2013-07-22             OZ                 1            2.50
17286 2013-07-22             OZ                 1            2.00
26456 2013-07-22             OZ                 3            7.50
5072  2013-07-22             OZ                 4            7.49
      2013-07-22             OZ                 2            5.98
17286 2013-07-22             OZ                 3           20.97
28840 2013-07-22             OZ                 1            3.99
26456 2013-07-22             OZ                 1            4.49
5072  2013-07-22             OZ                 1            2.99
3718  2013-07-22             OZ                 4           16.76
6926  2013-07-22             OZ                 2            3.18
15889 2013-07-23             OZ                 1            4.19
5072  2013-07-23             CT                 1            2.99
17286 2013-07-23             OZ                 1            5.95
5072  2013-07-23             OZ                 1            1.49
      2013-07-23             OZ                 1            2.99
      2013-07-23             OZ                 3            4.50
      2013-07-23             OZ                 3            4.50
28840 2013-07-23             OZ                 1            3.99
26456 2013-07-23             OZ                 2            5.00
      2013-07-23             OZ                 1            2.50
5072  2013-07-23             OZ                 1            2.99
6926  2013-07-23             OZ                 1            1.59
3718  2013-07-21             OZ                 1            9.99
875   2013-07-21             OZ                 2            6.98

[9253365 rows x 9 columns]

In [7]:
train_transaction_all3=pd.read_csv('transactions_reduced_all3_test.csv')
#print transaction

In [8]:
train_transaction_company_joined=pd.merge(train_transaction_company,trainHistory, on=['id','chain'])
train_transaction_company_joined.set_index(['id', 'chain', 'company', 'date'])

                                        dept  category  brand  productsize  \
id         chain company    date
12262064   95    103700030  2012-04-05    72      7203   4294        32.00
                            2012-05-25    34      3405  13012         8.50
                 1076211171 2012-06-09    36      3611   5923        23.70
                 103700030  2012-07-03    22      2210   5174        34.00
                 105100050  2012-07-11    51      5127   8605        16.00
                 104127141  2012-07-27     7       706  26189        64.00
                 105100050  2012-09-16    51      5127   8605        16.00
                 103700030  2012-09-29    26      2614    514        16.00
                            2012-09-30    18      1828   6236         0.18
                 105100050  2012-12-04    37      3705   2820        18.80
                 103700030  2012-12-04    18      1829   6236         1.00
                 107127979  2012-12-05    99      9909   6732         9.00
                            2012-12-05    99      9909   6732        12.00
                 105190050  2012-12-05    58      5837  26456         7.00
                 103700030  2012-12-11    35      3504   4628        20.00
                 107127979  2013-01-31    99      9909   6732         9.00
                 103700030  2013-04-18    35      3509   6947       137.00
                 108079383  2013-04-27     6       610  12778        16.00
                 104460040  2013-04-29    17      1709   3718        24.00
                            2013-04-29    17      1726   3718        35.00
                 105100050  2013-05-12    37      3711   2820        14.00
                            2013-05-15    37      3711   2820        14.00
                 103700030  2013-05-31    71      7110   8047        14.20
                            2013-06-06    26      2634   3293         9.00
                 108079383  2013-06-16    21      2118   6926        16.90
                 105100050  2013-06-25    37      3703   2820        26.00
12277270   95    1076211171 2012-03-05     7       708  17286        12.00
                 107127979  2012-03-09    99      9909   6732         8.00
                 103700030  2012-03-18    72      7203   4294        33.80
                 107127979  2012-03-18    99      9909   6732         6.00
...                                      ...       ...    ...          ...
4847628950 166   105100050  2013-07-22    37      3705   2820        18.80
                            2013-07-22    37      3703   2820        10.75
                 103700030  2013-07-22    71      7106   8047        14.20
                 105190050  2013-07-22    58      5823  26456         9.00
                 103700030  2013-07-22    26      2628   2248         8.00
                 1076211171 2013-07-22     7       709  17286         4.20
                 1089520383 2013-07-22    99      9909  28840         5.00
                 103700030  2013-07-22    35      3504   4628        20.00
                 105190050  2013-07-22    58      5823  26456        16.00
                 105100050  2013-07-22    37      3705   2820        19.00
                 103320030  2013-07-22    72      7205    305         6.00
                 103700030  2013-07-22    26      2634   3293        30.00
                 104460040  2013-07-22    22      2201   3718       121.00
                 108079383  2013-07-22    21      2118   6926        16.90
                 104610040  2013-07-23    56      5620  15889         8.00
                 1076211171 2013-07-23     7       703  17286         3.44
                 104460040  2013-07-23    27      2710   6743         7.00
                 105100050  2013-07-23    37      3703   2820        10.75
                 1089520383 2013-07-23    99      9909  28840         5.00
                 108500080  2013-07-23    64      6408  21942         0.75
                 105190050  2013-07-23    58      5823  26456         9.00
                            2013-07-23    58      5823  26456         7.50
                 108500080  2013-07-23    64      6408  13918         5.00
                 103700030  2013-07-23    22      2210   5174        51.00
                 108079383  2013-07-23    21      2118   6926        16.90
4847787712 46    104460040  2013-07-21    22      2207   3718        66.00
                 105100050  2013-07-21    37      3703   2820        10.50
                 103320030  2013-07-21    35      3509    875        75.00
4853460972 214   105100050  2013-07-20    20      2002  27873        33.60
                            2013-07-21    20      2002  27873        33.60

                                       productmeasure  purchasequantity  \
id         chain company    date
12262064   95    103700030  2012-04-05             OZ                 1
                            2012-05-25             OZ                 1
                 1076211171 2012-06-09             OZ                 1
                 103700030  2012-07-03             OZ                 1
                 105100050  2012-07-11             OZ                 1
                 104127141  2012-07-27             OZ                 1
                 105100050  2012-09-16             OZ                 1
                 103700030  2012-09-29             CT                 1
                            2012-09-30             OZ                 1
                 105100050  2012-12-04             OZ                 2
                 103700030  2012-12-04             CT                 1
                 107127979  2012-12-05             OZ                 1
                            2012-12-05             OZ                 1
                 105190050  2012-12-05             OZ                 1
                 103700030  2012-12-11             OZ                 1
                 107127979  2013-01-31             OZ                 1
                 103700030  2013-04-18             OZ                 1
                 108079383  2013-04-27             OZ                 1
                 104460040  2013-04-29             OZ                 1
                            2013-04-29             CT                 1
                 105100050  2013-05-12             OZ                 1
                            2013-05-15             OZ                 1
                 103700030  2013-05-31             OZ                 1
                            2013-06-06             RL                 1
                 108079383  2013-06-16             OZ                 1
                 105100050  2013-06-25             OZ                 2
12277270   95    1076211171 2012-03-05             OZ                 1
                 107127979  2012-03-09             OZ                 2
                 103700030  2012-03-18             OZ                 1
                 107127979  2012-03-18             OZ                 1
...                                               ...               ...
4847628950 166   105100050  2013-07-22             OZ                 1
                            2013-07-22             OZ                 3
                 103700030  2013-07-22             OZ                 1
                 105190050  2013-07-22             OZ                 3
                 103700030  2013-07-22             RL                 1
                 1076211171 2013-07-22             OZ                 3
                 1089520383 2013-07-22             OZ                 1
                 103700030  2013-07-22             OZ                 1
                 105190050  2013-07-22             OZ                 1
                 105100050  2013-07-22             OZ                 1
                 103320030  2013-07-22             OZ                 1
                 103700030  2013-07-22             RL                 1
                 104460040  2013-07-22             OZ                 4
                 108079383  2013-07-22             OZ                 2
                 104610040  2013-07-23             OZ                 1
                 1076211171 2013-07-23             OZ                 1
                 104460040  2013-07-23             LB                 1
                 105100050  2013-07-23             OZ                 1
                 1089520383 2013-07-23             OZ                 1
                 108500080  2013-07-23             LT                 1
                 105190050  2013-07-23             OZ                 2
                            2013-07-23             OZ                 1
                 108500080  2013-07-23             LT                 1
                 103700030  2013-07-23             OZ                 1
                 108079383  2013-07-23             OZ                 1
4847787712 46    104460040  2013-07-21             OZ                 1
                 105100050  2013-07-21             OZ                 1
                 103320030  2013-07-21             OZ                 2
4853460972 214   105100050  2013-07-20             OZ                 1
                            2013-07-21             OZ                 1

                                        purchaseamount    offer  market  \
id         chain company    date
12262064   95    103700030  2012-04-05            8.49  1219903      39
                            2012-05-25            2.99  1219903      39
                 1076211171 2012-06-09            1.95  1219903      39
                 103700030  2012-07-03            3.99  1219903      39
                 105100050  2012-07-11            2.99  1219903      39
                 104127141  2012-07-27            4.29  1219903      39
                 105100050  2012-09-16            3.49  1219903      39
                 103700030  2012-09-29            3.79  1219903      39
                            2012-09-30            0.99  1219903      39
                 105100050  2012-12-04            4.58  1219903      39
                 103700030  2012-12-04            4.50  1219903      39
                 107127979  2012-12-05            1.00  1219903      39
                            2012-12-05            1.00  1219903      39
                 105190050  2012-12-05            3.99  1219903      39
                 103700030  2012-12-11            3.79  1219903      39
                 107127979  2013-01-31            1.99  1219903      39
                 103700030  2013-04-18           16.99  1219903      39
                 108079383  2013-04-27            2.29  1219903      39
                 104460040  2013-04-29            2.00  1219903      39
                            2013-04-29            3.39  1219903      39
                 105100050  2013-05-12            2.89  1219903      39
                            2013-05-15            3.00  1219903      39
                 103700030  2013-05-31            4.99  1219903      39
                            2013-06-06           11.99  1219903      39
                 108079383  2013-06-16            1.59  1219903      39
                 105100050  2013-06-25            4.98  1219903      39
12277270   95    1076211171 2012-03-05            7.99  1221658      39
                 107127979  2012-03-09            3.98  1221658      39
                 103700030  2012-03-18            5.99  1221658      39
                 107127979  2012-03-18            2.69  1221658      39
...                                                ...      ...     ...
4847628950 166   105100050  2013-07-22            2.39  1230218      14
                            2013-07-22            5.37  1230218      14
                 103700030  2013-07-22            4.99  1230218      14
                 105190050  2013-07-22            7.50  1230218      14
                 103700030  2013-07-22           10.69  1230218      14
                 1076211171 2013-07-22           20.97  1230218      14
                 1089520383 2013-07-22            3.99  1230218      14
                 103700030  2013-07-22            3.79  1230218      14
                 105190050  2013-07-22            4.49  1230218      14
                 105100050  2013-07-22            2.39  1230218      14
                 103320030  2013-07-22            1.19  1230218      14
                 103700030  2013-07-22           19.99  1230218      14
                 104460040  2013-07-22           16.76  1230218      14
                 108079383  2013-07-22            3.18  1230218      14
                 104610040  2013-07-23            4.19  1230218      14
                 1076211171 2013-07-23            5.95  1230218      14
                 104460040  2013-07-23            3.69  1230218      14
                 105100050  2013-07-23            1.59  1230218      14
                 1089520383 2013-07-23            3.99  1230218      14
                 108500080  2013-07-23            5.99  1230218      14
                 105190050  2013-07-23            5.00  1230218      14
                            2013-07-23            2.50  1230218      14
                 108500080  2013-07-23           15.99  1230218      14
                 103700030  2013-07-23            6.79  1230218      14
                 108079383  2013-07-23            1.59  1230218      14
4847787712 46    104460040  2013-07-21            9.99  1230218      15
                 105100050  2013-07-21            1.66  1230218      15
                 103320030  2013-07-21            6.98  1230218      15
4853460972 214   105100050  2013-07-20            2.98  1230218       8
                            2013-07-21            2.98  1230218       8

                                         offerdate
id         chain company    date
12262064   95    103700030  2012-04-05  2013-06-27
                            2012-05-25  2013-06-27
                 1076211171 2012-06-09  2013-06-27
                 103700030  2012-07-03  2013-06-27
                 105100050  2012-07-11  2013-06-27
                 104127141  2012-07-27  2013-06-27
                 105100050  2012-09-16  2013-06-27
                 103700030  2012-09-29  2013-06-27
                            2012-09-30  2013-06-27
                 105100050  2012-12-04  2013-06-27
                 103700030  2012-12-04  2013-06-27
                 107127979  2012-12-05  2013-06-27
                            2012-12-05  2013-06-27
                 105190050  2012-12-05  2013-06-27
                 103700030  2012-12-11  2013-06-27
                 107127979  2013-01-31  2013-06-27
                 103700030  2013-04-18  2013-06-27
                 108079383  2013-04-27  2013-06-27
                 104460040  2013-04-29  2013-06-27
                            2013-04-29  2013-06-27
                 105100050  2013-05-12  2013-06-27
                            2013-05-15  2013-06-27
                 103700030  2013-05-31  2013-06-27
                            2013-06-06  2013-06-27
                 108079383  2013-06-16  2013-06-27
                 105100050  2013-06-25  2013-06-27
12277270   95    1076211171 2012-03-05  2013-06-23
                 107127979  2012-03-09  2013-06-23
                 103700030  2012-03-18  2013-06-23
                 107127979  2012-03-18  2013-06-23
...                                            ...
4847628950 166   105100050  2013-07-22  2013-07-24
                            2013-07-22  2013-07-24
                 103700030  2013-07-22  2013-07-24
                 105190050  2013-07-22  2013-07-24
                 103700030  2013-07-22  2013-07-24
                 1076211171 2013-07-22  2013-07-24
                 1089520383 2013-07-22  2013-07-24
                 103700030  2013-07-22  2013-07-24
                 105190050  2013-07-22  2013-07-24
                 105100050  2013-07-22  2013-07-24
                 103320030  2013-07-22  2013-07-24
                 103700030  2013-07-22  2013-07-24
                 104460040  2013-07-22  2013-07-24
                 108079383  2013-07-22  2013-07-24
                 104610040  2013-07-23  2013-07-24
                 1076211171 2013-07-23  2013-07-24
                 104460040  2013-07-23  2013-07-24
                 105100050  2013-07-23  2013-07-24
                 1089520383 2013-07-23  2013-07-24
                 108500080  2013-07-23  2013-07-24
                 105190050  2013-07-23  2013-07-24
                            2013-07-23  2013-07-24
                 108500080  2013-07-23  2013-07-24
                 103700030  2013-07-23  2013-07-24
                 108079383  2013-07-23  2013-07-24
4847787712 46    104460040  2013-07-21  2013-07-26
                 105100050  2013-07-21  2013-07-26
                 103320030  2013-07-21  2013-07-26
4853460972 214   105100050  2013-07-20  2013-07-28
                            2013-07-21  2013-07-28

[7392167 rows x 10 columns]

In [9]:
train_transaction_category_joined=pd.merge(train_transaction_category,trainHistory, on=['id','chain'])
train_transaction_category_joined.set_index(['id', 'chain', 'category', 'date'])

                                      dept     company  brand  productsize  \
id         chain category date
12262064   95    2119     2012-05-07    21   107618373  16756        32.00
                          2012-06-09    21  1061300868    867        23.00
                          2012-06-09    21   101200010  10522        33.80
                 9909     2012-06-12    99   102113020  15704         9.00
                 5824     2012-06-13    58  1075290777  54853        16.00
                 9909     2012-06-14    99   102113020  16397        10.75
                 706      2012-06-15     7   101200010  17286        13.70
                 5558     2012-06-18    55   107255474  35506        18.10
                 5824     2012-07-02    58  1076401474    304        12.00
                 2119     2012-07-12    21  1073951070  16807        20.00
                 9909     2012-07-27    99   107989373  12908        16.00
                 706      2012-07-27     7   104127141  26189        64.00
                 2119     2012-08-09    21  1083812888  23042        23.50
                          2012-08-13    21  1083812888  23042        23.50
                 5616     2012-08-18    56   102113020   4720         8.00
                 2119     2012-08-22    21  1083812888  23042        23.50
                 5824     2012-08-28    58   107778272   9260        12.00
                 5616     2012-08-29    56   102113020   4720         8.00
                 2119     2012-09-03    21  1083812888  23042        23.50
                 1703     2012-09-03    17   101980010  19934        26.00
                 2119     2012-09-06    21  1083812888  23042        23.50
                          2012-09-13    21   101200010  10522        20.00
                          2012-09-19    21   107618373  16756        32.00
                 5824     2012-10-16    58   102113020  15704        16.00
                 9909     2012-12-05    99   107127979   6732         9.00
                          2012-12-05    99   107127979   6732        12.00
                 3504     2012-12-11    35   103700030   4628        20.00
                 9909     2013-01-31    99   102791828  53783         1.00
                          2013-01-31    99   107127979   6732         9.00
                 2119     2013-02-09    21  1083812888  23042        23.50
...                                    ...         ...    ...          ...
4847628950 166   3504     2013-07-22    35   103500030    330        30.00
                 9115     2013-07-22    91   108954080  11045         0.75
                 7205     2013-07-22    72   103320030    305         6.00
                 2119     2013-07-22    21   101200010  10522        24.00
                 3509     2013-07-23    35   102420020  14716        43.50
                 5558     2013-07-23    55   107064070  14205        42.00
                 2119     2013-07-23    21   107084777  32541        23.00
                 6202     2013-07-23    62  1074275373  13609         8.00
                 5558     2013-07-23    55   107064070  14205        13.50
                 2119     2013-07-23    21  1061300868    867        23.00
                 9909     2013-07-23    99   103190333   1436        10.50
                 1703     2013-07-23    17   103680030   6561        32.00
                 5616     2013-07-23    56   107283070  18390        12.00
                 9115     2013-07-23    91   108200080   2911         0.75
                 9909     2013-07-23    99   107143070   5072         8.00
                          2013-07-23    99   107143070   5072         5.00
                          2013-07-23    99   107143070   5072         9.00
                          2013-07-23    99   107143070   5072        12.00
                 2119     2013-07-23    21  1065762262  26129        16.00
                 9115     2013-07-23    91   108700080   2911         1.75
                 9909     2013-07-23    99  1089520383  28840         5.00
                 3509     2013-07-23    35   102420020  14716       150.00
                          2013-07-23    35   107261373  17576        75.00
                 5824     2013-07-23    58   104274343   5653         9.00
                 2119     2013-07-23    21   101200010  10522       128.00
                 5824     2013-07-23    58  1076401474    304        12.00
4847787712 46    2119     2013-07-21    21  1088692686  11473       128.00
                 3509     2013-07-21    35   103320030    875        75.00
4853598737 46    5558     2013-07-20    55   104154848   5603         5.80
                 5824     2013-07-20    58   104660040   5557        14.00

                                     productmeasure  purchasequantity  \
id         chain category date
12262064   95    2119     2012-05-07             OZ                 1
                          2012-06-09             OZ                 0
                          2012-06-09             OZ                 1
                 9909     2012-06-12             OZ                 2
                 5824     2012-06-13             OZ                 1
                 9909     2012-06-14             OZ                 1
                 706      2012-06-15             OZ                 2
                 5558     2012-06-18             OZ                 1
                 5824     2012-07-02             OZ                 1
                 2119     2012-07-12             OZ                 1
                 9909     2012-07-27             OZ                 1
                 706      2012-07-27             OZ                 1
                 2119     2012-08-09             OZ                 1
                          2012-08-13             OZ                 1
                 5616     2012-08-18             OZ                 2
                 2119     2012-08-22             OZ                 1
                 5824     2012-08-28             OZ                 1
                 5616     2012-08-29             OZ                 1
                 2119     2012-09-03             OZ                 1
                 1703     2012-09-03             OZ                 1
                 2119     2012-09-06             OZ                 1
                          2012-09-13             OZ                 1
                          2012-09-19             OZ                 1
                 5824     2012-10-16             OZ                 1
                 9909     2012-12-05             OZ                 1
                          2012-12-05             OZ                 1
                 3504     2012-12-11             OZ                 1
                 9909     2013-01-31             CT                 2
                          2013-01-31             OZ                 1
                 2119     2013-02-09             OZ                 1
...                                             ...               ...
4847628950 166   3504     2013-07-22             OZ                 1
                 9115     2013-07-22             LT                 1
                 7205     2013-07-22             OZ                 1
                 2119     2013-07-22             OZ                 3
                 3509     2013-07-23             OZ                 1
                 5558     2013-07-23             OZ                 1
                 2119     2013-07-23             OZ                 3
                 6202     2013-07-23             OZ                 2
                 5558     2013-07-23             OZ                 1
                 2119     2013-07-23             OZ                 3
                 9909     2013-07-23             OZ                 1
                 1703     2013-07-23             OZ                 1
                 5616     2013-07-23             OZ                 1
                 9115     2013-07-23             LT                 1
                 9909     2013-07-23             OZ                 1
                          2013-07-23             OZ                 1
                          2013-07-23             OZ                 3
                          2013-07-23             OZ                 3
                 2119     2013-07-23             OZ                 1
                 9115     2013-07-23             LT                 1
                 9909     2013-07-23             OZ                 1
                 3509     2013-07-23             OZ                 1
                          2013-07-23             OZ                 1
                 5824     2013-07-23             OZ                 1
                 2119     2013-07-23             OZ                 2
                 5824     2013-07-23             OZ                 1
4847787712 46    2119     2013-07-21             OZ                 1
                 3509     2013-07-21             OZ                 2
4853598737 46    5558     2013-07-20             OZ                 3
                 5824     2013-07-20             OZ                 1

                                      purchaseamount    offer  market  \
id         chain category date
12262064   95    2119     2012-05-07            1.99  1219903      39
                          2012-06-09            0.00  1219903      39
                          2012-06-09            1.50  1219903      39
                 9909     2012-06-12            4.00  1219903      39
                 5824     2012-06-13            4.19  1219903      39
                 9909     2012-06-14            4.99  1219903      39
                 706      2012-06-15            4.00  1219903      39
                 5558     2012-06-18            3.34  1219903      39
                 5824     2012-07-02            4.99  1219903      39
                 2119     2012-07-12            1.89  1219903      39
                 9909     2012-07-27            4.99  1219903      39
                 706      2012-07-27            4.29  1219903      39
                 2119     2012-08-09            1.49  1219903      39
                          2012-08-13            1.49  1219903      39
                 5616     2012-08-18            9.48  1219903      39
                 2119     2012-08-22            1.49  1219903      39
                 5824     2012-08-28            2.29  1219903      39
                 5616     2012-08-29            4.49  1219903      39
                 2119     2012-09-03            1.49  1219903      39
                 1703     2012-09-03            3.49  1219903      39
                 2119     2012-09-06            1.49  1219903      39
                          2012-09-13            1.99  1219903      39
                          2012-09-19           -0.31  1219903      39
                 5824     2012-10-16            3.29  1219903      39
                 9909     2012-12-05            1.00  1219903      39
                          2012-12-05            1.00  1219903      39
                 3504     2012-12-11            3.79  1219903      39
                 9909     2013-01-31            5.38  1219903      39
                          2013-01-31            1.99  1219903      39
                 2119     2013-02-09            1.00  1219903      39
...                                              ...      ...     ...
4847628950 166   3504     2013-07-22            2.59  1230218      14
                 9115     2013-07-22           11.99  1230218      14
                 7205     2013-07-22            1.19  1230218      14
                 2119     2013-07-22            2.64  1230218      14
                 3509     2013-07-23            4.79  1230218      14
                 5558     2013-07-23            3.99  1230218      14
                 2119     2013-07-23            2.97  1230218      14
                 6202     2013-07-23            9.98  1230218      14
                 5558     2013-07-23            2.50  1230218      14
                 2119     2013-07-23            2.37  1230218      14
                 9909     2013-07-23            4.99  1230218      14
                 1703     2013-07-23            2.19  1230218      14
                 5616     2013-07-23            5.49  1230218      14
                 9115     2013-07-23           14.99  1230218      14
                 9909     2013-07-23            1.49  1230218      14
                          2013-07-23            2.99  1230218      14
                          2013-07-23            4.50  1230218      14
                          2013-07-23            4.50  1230218      14
                 2119     2013-07-23            1.99  1230218      14
                 9115     2013-07-23           27.99  1230218      14
                 9909     2013-07-23            3.99  1230218      14
                 3509     2013-07-23            8.99  1230218      14
                          2013-07-23            2.99  1230218      14
                 5824     2013-07-23            1.49  1230218      14
                 2119     2013-07-23            5.00  1230218      14
                 5824     2013-07-23            5.99  1230218      14
4847787712 46    2119     2013-07-21            1.99  1230218      15
                 3509     2013-07-21            6.98  1230218      15
4853598737 46    5558     2013-07-20            3.00  1230218      15
                 5824     2013-07-20            2.79  1230218      15

                                       offerdate
id         chain category date
12262064   95    2119     2012-05-07  2013-06-27
                          2012-06-09  2013-06-27
                          2012-06-09  2013-06-27
                 9909     2012-06-12  2013-06-27
                 5824     2012-06-13  2013-06-27
                 9909     2012-06-14  2013-06-27
                 706      2012-06-15  2013-06-27
                 5558     2012-06-18  2013-06-27
                 5824     2012-07-02  2013-06-27
                 2119     2012-07-12  2013-06-27
                 9909     2012-07-27  2013-06-27
                 706      2012-07-27  2013-06-27
                 2119     2012-08-09  2013-06-27
                          2012-08-13  2013-06-27
                 5616     2012-08-18  2013-06-27
                 2119     2012-08-22  2013-06-27
                 5824     2012-08-28  2013-06-27
                 5616     2012-08-29  2013-06-27
                 2119     2012-09-03  2013-06-27
                 1703     2012-09-03  2013-06-27
                 2119     2012-09-06  2013-06-27
                          2012-09-13  2013-06-27
                          2012-09-19  2013-06-27
                 5824     2012-10-16  2013-06-27
                 9909     2012-12-05  2013-06-27
                          2012-12-05  2013-06-27
                 3504     2012-12-11  2013-06-27
                 9909     2013-01-31  2013-06-27
                          2013-01-31  2013-06-27
                 2119     2013-02-09  2013-06-27
...                                          ...
4847628950 166   3504     2013-07-22  2013-07-24
                 9115     2013-07-22  2013-07-24
                 7205     2013-07-22  2013-07-24
                 2119     2013-07-22  2013-07-24
                 3509     2013-07-23  2013-07-24
                 5558     2013-07-23  2013-07-24
                 2119     2013-07-23  2013-07-24
                 6202     2013-07-23  2013-07-24
                 5558     2013-07-23  2013-07-24
                 2119     2013-07-23  2013-07-24
                 9909     2013-07-23  2013-07-24
                 1703     2013-07-23  2013-07-24
                 5616     2013-07-23  2013-07-24
                 9115     2013-07-23  2013-07-24
                 9909     2013-07-23  2013-07-24
                          2013-07-23  2013-07-24
                          2013-07-23  2013-07-24
                          2013-07-23  2013-07-24
                 2119     2013-07-23  2013-07-24
                 9115     2013-07-23  2013-07-24
                 9909     2013-07-23  2013-07-24
                 3509     2013-07-23  2013-07-24
                          2013-07-23  2013-07-24
                 5824     2013-07-23  2013-07-24
                 2119     2013-07-23  2013-07-24
                 5824     2013-07-23  2013-07-24
4847787712 46    2119     2013-07-21  2013-07-26
                 3509     2013-07-21  2013-07-26
4853598737 46    5558     2013-07-20  2013-07-27
                 5824     2013-07-20  2013-07-27

[6928974 rows x 10 columns]

In [10]:
train_transaction_brand_joined=pd.merge(train_transaction_brand,trainHistory, on=['id','chain'])
train_transaction_brand_joined.set_index(['id', 'chain', 'brand', 'date'])

                                   dept  category     company  productsize  \
id         chain brand date
12262064   95    4294  2012-04-05    72      7203   103700030        32.00
                 17286 2012-06-15     7       706   101200010        13.70
                 26189 2012-07-27     7       706   104127141        64.00
                 13791 2012-11-27     9       905   101410010        12.00
                       2012-12-01     9       905   101410010        12.00
                 6732  2012-12-05    99      9909   107127979         9.00
                       2012-12-05    99      9909   107127979        12.00
                 26456 2012-12-05    58      5837   105190050         7.00
                 17286 2012-12-23    96      9632   107675070         1.00
                 6732  2013-01-31    99      9909   107127979         9.00
                 3718  2013-04-29    17      1709   104460040        24.00
                       2013-04-29    17      1726   104460040        35.00
                 17286 2013-05-24     7       706   101200010        13.70
                 875   2013-06-06    72      7212  1076687878         1.00
                 6926  2013-06-16    21      2118   108079383        16.90
12277270   95    17286 2012-03-05     7       708  1076211171        12.00
                 6732  2012-03-09    99      9909   107127979         8.00
                 4294  2012-03-18    72      7203   103700030        33.80
                 6732  2012-03-18    99      9909   107127979         6.00
                 875   2012-03-31    27      2710   103320030        20.00
                 4294  2012-03-31    72      7205   103700030         6.00
                 6732  2012-04-02    99      9909   107127979        16.00
                 13474 2012-04-08    32      3203   106414464         5.00
                 17286 2012-04-21     7       708  1076211171        16.00
                 4294  2012-04-21    72      7203   103700030        33.80
                 875   2012-04-21     3       305   103320030        16.00
                 6732  2012-04-21    99      9909   107127979         6.00
                 17286 2012-05-06     7       708  1076211171        16.00
                 6732  2012-05-06    99      9909   107127979         6.00
                       2012-05-15    99      9909   107127979         8.00
...                                 ...       ...         ...          ...
4847628950 166   15889 2013-07-21    56      5616   104610040         7.60
                 5072  2013-07-21    99      9909   107143070         9.00
                       2013-07-21    99      9909   107143070        11.00
                 4294  2013-07-21    72      7205   103700030         6.40
                 17286 2013-07-22     7       703  1076211171         3.68
                 26456 2013-07-22    58      5823   105190050        10.00
                 17286 2013-07-22     7       706   101200010        15.00
                 26456 2013-07-22    58      5823   105190050         9.00
                 5072  2013-07-22    99      9909   107143070         9.00
                       2013-07-22    99      9909   107143070         9.90
                 17286 2013-07-22     7       709  1076211171         4.20
                 28840 2013-07-22    99      9909  1089520383         5.00
                 26456 2013-07-22    58      5823   105190050        16.00
                 5072  2013-07-22    63      6311   104850040        59.00
                 3718  2013-07-22    22      2201   104460040       121.00
                 6926  2013-07-22    21      2118   108079383        16.90
                 15889 2013-07-23    56      5620   104610040         8.00
                 5072  2013-07-23    99      9904  1064312666         1.00
                 17286 2013-07-23     7       703  1076211171         3.44
                 5072  2013-07-23    99      9909   107143070         8.00
                       2013-07-23    99      9909   107143070         5.00
                       2013-07-23    99      9909   107143070         9.00
                       2013-07-23    99      9909   107143070        12.00
                 28840 2013-07-23    99      9909  1089520383         5.00
                 26456 2013-07-23    58      5823   105190050         9.00
                       2013-07-23    58      5823   105190050         7.50
                 5072  2013-07-23    63      6311   104850040        59.00
                 6926  2013-07-23    21      2118   108079383        16.90
4847787712 46    3718  2013-07-21    22      2207   104460040        66.00
                 875   2013-07-21    35      3509   103320030        75.00

                                  productmeasure  purchasequantity  \
id         chain brand date
12262064   95    4294  2012-04-05             OZ                 1
                 17286 2012-06-15             OZ                 2
                 26189 2012-07-27             OZ                 1
                 13791 2012-11-27             OZ                 1
                       2012-12-01             OZ                 2
                 6732  2012-12-05             OZ                 1
                       2012-12-05             OZ                 1
                 26456 2012-12-05             OZ                 1
                 17286 2012-12-23             CT                 1
                 6732  2013-01-31             OZ                 1
                 3718  2013-04-29             OZ                 1
                       2013-04-29             CT                 1
                 17286 2013-05-24             OZ                 1
                 875   2013-06-06             CT                 1
                 6926  2013-06-16             OZ                 1
12277270   95    17286 2012-03-05             OZ                 1
                 6732  2012-03-09             OZ                 2
                 4294  2012-03-18             OZ                 1
                 6732  2012-03-18             OZ                 1
                 875   2012-03-31             LB                 1
                 4294  2012-03-31             OZ                 1
                 6732  2012-04-02             OZ                 1
                 13474 2012-04-08             OZ                 1
                 17286 2012-04-21             OZ                 1
                 4294  2012-04-21             OZ                 1
                 875   2012-04-21             OZ                 1
                 6732  2012-04-21             OZ                 1
                 17286 2012-05-06             OZ                 1
                 6732  2012-05-06             OZ                 1
                       2012-05-15             OZ                 1
...                                          ...               ...
4847628950 166   15889 2013-07-21             OZ                 1
                 5072  2013-07-21             OZ                 3
                       2013-07-21             OZ                 2
                 4294  2013-07-21             OZ                 1
                 17286 2013-07-22             OZ                 1
                 26456 2013-07-22             OZ                 1
                 17286 2013-07-22             OZ                 1
                 26456 2013-07-22             OZ                 3
                 5072  2013-07-22             OZ                 4
                       2013-07-22             OZ                 2
                 17286 2013-07-22             OZ                 3
                 28840 2013-07-22             OZ                 1
                 26456 2013-07-22             OZ                 1
                 5072  2013-07-22             OZ                 1
                 3718  2013-07-22             OZ                 4
                 6926  2013-07-22             OZ                 2
                 15889 2013-07-23             OZ                 1
                 5072  2013-07-23             CT                 1
                 17286 2013-07-23             OZ                 1
                 5072  2013-07-23             OZ                 1
                       2013-07-23             OZ                 1
                       2013-07-23             OZ                 3
                       2013-07-23             OZ                 3
                 28840 2013-07-23             OZ                 1
                 26456 2013-07-23             OZ                 2
                       2013-07-23             OZ                 1
                 5072  2013-07-23             OZ                 1
                 6926  2013-07-23             OZ                 1
4847787712 46    3718  2013-07-21             OZ                 1
                 875   2013-07-21             OZ                 2

                                   purchaseamount    offer  market   offerdate
id         chain brand date
12262064   95    4294  2012-04-05            8.49  1219903      39  2013-06-27
                 17286 2012-06-15            4.00  1219903      39  2013-06-27
                 26189 2012-07-27            4.29  1219903      39  2013-06-27
                 13791 2012-11-27            3.39  1219903      39  2013-06-27
                       2012-12-01            6.98  1219903      39  2013-06-27
                 6732  2012-12-05            1.00  1219903      39  2013-06-27
                       2012-12-05            1.00  1219903      39  2013-06-27
                 26456 2012-12-05            3.99  1219903      39  2013-06-27
                 17286 2012-12-23           50.00  1219903      39  2013-06-27
                 6732  2013-01-31            1.99  1219903      39  2013-06-27
                 3718  2013-04-29            2.00  1219903      39  2013-06-27
                       2013-04-29            3.39  1219903      39  2013-06-27
                 17286 2013-05-24            2.79  1219903      39  2013-06-27
                 875   2013-06-06            7.99  1219903      39  2013-06-27
                 6926  2013-06-16            1.59  1219903      39  2013-06-27
12277270   95    17286 2012-03-05            7.99  1221658      39  2013-06-23
                 6732  2012-03-09            3.98  1221658      39  2013-06-23
                 4294  2012-03-18            5.99  1221658      39  2013-06-23
                 6732  2012-03-18            2.69  1221658      39  2013-06-23
                 875   2012-03-31            3.59  1221658      39  2013-06-23
                 4294  2012-03-31            3.49  1221658      39  2013-06-23
                 6732  2012-04-02            2.99  1221658      39  2013-06-23
                 13474 2012-04-08            3.49  1221658      39  2013-06-23
                 17286 2012-04-21           12.95  1221658      39  2013-06-23
                 4294  2012-04-21            5.74  1221658      39  2013-06-23
                 875   2012-04-21            1.29  1221658      39  2013-06-23
                 6732  2012-04-21            2.29  1221658      39  2013-06-23
                 17286 2012-05-06           13.95  1221658      39  2013-06-23
                 6732  2012-05-06            2.29  1221658      39  2013-06-23
                       2012-05-15            1.99  1221658      39  2013-06-23
...                                           ...      ...     ...         ...
4847628950 166   15889 2013-07-21            3.99  1230218      14  2013-07-24
                 5072  2013-07-21            4.50  1230218      14  2013-07-24
                       2013-07-21            7.98  1230218      14  2013-07-24
                 4294  2013-07-21            1.49  1230218      14  2013-07-24
                 17286 2013-07-22            5.95  1230218      14  2013-07-24
                 26456 2013-07-22            2.50  1230218      14  2013-07-24
                 17286 2013-07-22            2.00  1230218      14  2013-07-24
                 26456 2013-07-22            7.50  1230218      14  2013-07-24
                 5072  2013-07-22            7.49  1230218      14  2013-07-24
                       2013-07-22            5.98  1230218      14  2013-07-24
                 17286 2013-07-22           20.97  1230218      14  2013-07-24
                 28840 2013-07-22            3.99  1230218      14  2013-07-24
                 26456 2013-07-22            4.49  1230218      14  2013-07-24
                 5072  2013-07-22            2.99  1230218      14  2013-07-24
                 3718  2013-07-22           16.76  1230218      14  2013-07-24
                 6926  2013-07-22            3.18  1230218      14  2013-07-24
                 15889 2013-07-23            4.19  1230218      14  2013-07-24
                 5072  2013-07-23            2.99  1230218      14  2013-07-24
                 17286 2013-07-23            5.95  1230218      14  2013-07-24
                 5072  2013-07-23            1.49  1230218      14  2013-07-24
                       2013-07-23            2.99  1230218      14  2013-07-24
                       2013-07-23            4.50  1230218      14  2013-07-24
                       2013-07-23            4.50  1230218      14  2013-07-24
                 28840 2013-07-23            3.99  1230218      14  2013-07-24
                 26456 2013-07-23            5.00  1230218      14  2013-07-24
                       2013-07-23            2.50  1230218      14  2013-07-24
                 5072  2013-07-23            2.99  1230218      14  2013-07-24
                 6926  2013-07-23            1.59  1230218      14  2013-07-24
4847787712 46    3718  2013-07-21            9.99  1230218      15  2013-07-26
                 875   2013-07-21            6.98  1230218      15  2013-07-26

[4123223 rows x 10 columns]

In [11]:
train_transaction_all_joined=pd.merge(train_transaction_all3,trainHistory, on=['id','chain'])
train_transaction_all_joined.set_index(['id', 'chain', 'category','date'])

                                      dept     company  brand  productsize  \
id         chain category date
12262064   95    706      2012-07-27     7   104127141  26189        64.00
                 9909     2012-12-05    99   107127979   6732         9.00
                          2012-12-05    99   107127979   6732        12.00
                          2013-01-31    99   107127979   6732         9.00
12277270   95    9909     2012-03-09    99   107127979   6732         8.00
                          2012-03-18    99   107127979   6732         6.00
                 7205     2012-03-31    72   103700030   4294         6.00
                 9909     2012-04-02    99   107127979   6732        16.00
                 3203     2012-04-08    32   106414464  13474         5.00
                 9909     2012-04-21    99   107127979   6732         6.00
                          2012-05-06    99   107127979   6732         6.00
                          2012-05-15    99   107127979   6732         8.00
                          2012-05-30    99   107127979   6732        16.00
                          2012-06-02    99   107127979   6732         6.00
                          2012-06-30    99   107127979   6732         6.00
                          2012-07-06    99   107127979   6732        16.00
                          2012-07-11    99   107127979   6732         8.00
                          2012-07-12    99   107127979   6732         8.00
                          2012-07-18    99   107127979   6732        16.00
                          2012-07-23    99   107127979   6732         8.00
                          2012-07-25    99   107127979   6732         8.00
                          2012-07-30    99   107127979   6732         8.00
                          2012-08-01    99   107127979   6732         8.00
                          2012-08-04    99   107127979   6732         8.00
                          2012-08-24    99   107127979   6732         8.00
                          2012-09-11    99   107127979   6732        16.00
                          2012-09-21    99   107127979   6732         6.00
                 3509     2012-09-29    35   103320030    875       125.00
                 9909     2012-10-11    99   107127979   6732         8.00
                          2012-10-18    99   107127979   6732         8.00
...                                    ...         ...    ...          ...
4813248649 40    3203     2013-06-27    32   106414464  13474         5.00
                 5616     2013-06-28    56   104610040  15889         7.50
                          2013-06-29    56   104610040  15889         7.00
                          2013-06-29    56   104610040  15889         7.60
                 706      2013-06-30     7   104127141  26189        64.00
                 3203     2013-06-30    32   106414464  13474         6.00
                 7205     2013-06-30    72   103700030   4294         6.00
                 5122     2013-06-30    51   107106878  17311        42.72
                 3509     2013-06-30    35   103320030    875        50.00
                 5616     2013-07-03    56   104610040  15889         7.60
                          2013-07-03    56   104610040  15889         6.84
                 3509     2013-07-07    35   103320030    875        62.50
                 7205     2013-07-08    72   103700030   4294         4.20
                 5616     2013-07-13    56   104610040  15889         7.60
                 3203     2013-07-13    32   106414464  13474         5.00
                 7205     2013-07-15    72   103700030   4294         8.00
                          2013-07-16    72   103700030   4294         3.50
                 3203     2013-07-18    32   106414464  13474         8.00
                 5616     2013-07-20    56   104610040  15889         7.60
                          2013-07-20    56   104610040  15889         6.67
                          2013-07-20    56   104610040  15889         7.50
                 5122     2013-07-20    51   107106878  17311        32.00
                          2013-07-20    51   107106878  17311        42.72
                 5616     2013-07-21    56   104610040  15889         7.60
                 7205     2013-07-21    72   103700030   4294         4.20
4847628950 166   5616     2013-07-21    56   104610040  15889         7.60
                 7205     2013-07-21    72   103700030   4294         6.40
                 9909     2013-07-22    99  1089520383  28840         5.00
                          2013-07-23    99  1089520383  28840         5.00
4847787712 46    3509     2013-07-21    35   103320030    875        75.00

                                     productmeasure  purchasequantity  \
id         chain category date
12262064   95    706      2012-07-27             OZ                 1
                 9909     2012-12-05             OZ                 1
                          2012-12-05             OZ                 1
                          2013-01-31             OZ                 1
12277270   95    9909     2012-03-09             OZ                 2
                          2012-03-18             OZ                 1
                 7205     2012-03-31             OZ                 1
                 9909     2012-04-02             OZ                 1
                 3203     2012-04-08             OZ                 1
                 9909     2012-04-21             OZ                 1
                          2012-05-06             OZ                 1
                          2012-05-15             OZ                 1
                          2012-05-30             OZ                 1
                          2012-06-02             OZ                 1
                          2012-06-30             OZ                 1
                          2012-07-06             OZ                 1
                          2012-07-11             OZ                 1
                          2012-07-12             OZ                 1
                          2012-07-18             OZ                 1
                          2012-07-23             OZ                 1
                          2012-07-25             OZ                 1
                          2012-07-30             OZ                 1
                          2012-08-01             OZ                 2
                          2012-08-04             OZ                 1
                          2012-08-24             OZ                 1
                          2012-09-11             OZ                 2
                          2012-09-21             OZ                 1
                 3509     2012-09-29             OZ                 1
                 9909     2012-10-11             OZ                 1
                          2012-10-18             OZ                 2
...                                             ...               ...
4813248649 40    3203     2013-06-27             OZ                 1
                 5616     2013-06-28             OZ                 1
                          2013-06-29             OZ                 1
                          2013-06-29             OZ                 1
                 706      2013-06-30             OZ                 1
                 3203     2013-06-30             OZ                 1
                 7205     2013-06-30             OZ                 1
                 5122     2013-06-30             OZ                 1
                 3509     2013-06-30             OZ                 1
                 5616     2013-07-03             OZ                 1
                          2013-07-03             OZ                 1
                 3509     2013-07-07             OZ                 1
                 7205     2013-07-08             OZ                 1
                 5616     2013-07-13             OZ                 1
                 3203     2013-07-13             OZ                 1
                 7205     2013-07-15             OZ                 1
                          2013-07-16             OZ                 1
                 3203     2013-07-18             OZ                 1
                 5616     2013-07-20             OZ                 1
                          2013-07-20             OZ                 1
                          2013-07-20             OZ                 2
                 5122     2013-07-20             OZ                 1
                          2013-07-20             OZ                 1
                 5616     2013-07-21             OZ                 1
                 7205     2013-07-21             OZ                 1
4847628950 166   5616     2013-07-21             OZ                 1
                 7205     2013-07-21             OZ                 1
                 9909     2013-07-22             OZ                 1
                          2013-07-23             OZ                 1
4847787712 46    3509     2013-07-21             OZ                 2

                                      purchaseamount    offer  market  \
id         chain category date
12262064   95    706      2012-07-27            4.29  1219903      39
                 9909     2012-12-05            1.00  1219903      39
                          2012-12-05            1.00  1219903      39
                          2013-01-31            1.99  1219903      39
12277270   95    9909     2012-03-09            3.98  1221658      39
                          2012-03-18            2.69  1221658      39
                 7205     2012-03-31            3.49  1221658      39
                 9909     2012-04-02            2.99  1221658      39
                 3203     2012-04-08            3.49  1221658      39
                 9909     2012-04-21            2.29  1221658      39
                          2012-05-06            2.29  1221658      39
                          2012-05-15            1.99  1221658      39
                          2012-05-30            2.99  1221658      39
                          2012-06-02            2.79  1221658      39
                          2012-06-30            2.50  1221658      39
                          2012-07-06            2.99  1221658      39
                          2012-07-11            1.99  1221658      39
                          2012-07-12            1.99  1221658      39
                          2012-07-18            2.99  1221658      39
                          2012-07-23            1.99  1221658      39
                          2012-07-25            0.99  1221658      39
                          2012-07-30            0.49  1221658      39
                          2012-08-01            2.98  1221658      39
                          2012-08-04            1.49  1221658      39
                          2012-08-24            0.99  1221658      39
                          2012-09-11            4.08  1221658      39
                          2012-09-21            2.29  1221658      39
                 3509     2012-09-29           11.99  1221658      39
                 9909     2012-10-11            1.49  1221658      39
                          2012-10-18            2.98  1221658      39
...                                              ...      ...     ...
4813248649 40    3203     2013-06-27            3.29  1230218      23
                 5616     2013-06-28            3.49  1230218      23
                          2013-06-29            3.49  1230218      23
                          2013-06-29            3.49  1230218      23
                 706      2013-06-30            3.99  1230218      23
                 3203     2013-06-30            3.29  1230218      23
                 7205     2013-06-30            3.59  1230218      23
                 5122     2013-06-30            8.99  1230218      23
                 3509     2013-06-30            4.99  1230218      23
                 5616     2013-07-03            3.49  1230218      23
                          2013-07-03            3.49  1230218      23
                 3509     2013-07-07            6.79  1230218      23
                 7205     2013-07-08            3.79  1230218      23
                 5616     2013-07-13            3.29  1230218      23
                 3203     2013-07-13            3.29  1230218      23
                 7205     2013-07-15            4.39  1230218      23
                          2013-07-16            1.49  1230218      23
                 3203     2013-07-18            4.29  1230218      23
                 5616     2013-07-20            3.29  1230218      23
                          2013-07-20            3.29  1230218      23
                          2013-07-20            6.58  1230218      23
                 5122     2013-07-20            8.99  1230218      23
                          2013-07-20            8.99  1230218      23
                 5616     2013-07-21            3.29  1230218      23
                 7205     2013-07-21            3.79  1230218      23
4847628950 166   5616     2013-07-21            3.99  1230218      14
                 7205     2013-07-21            1.49  1230218      14
                 9909     2013-07-22            3.99  1230218      14
                          2013-07-23            3.99  1230218      14
4847787712 46    3509     2013-07-21            6.98  1230218      15

                                       offerdate
id         chain category date
12262064   95    706      2012-07-27  2013-06-27
                 9909     2012-12-05  2013-06-27
                          2012-12-05  2013-06-27
                          2013-01-31  2013-06-27
12277270   95    9909     2012-03-09  2013-06-23
                          2012-03-18  2013-06-23
                 7205     2012-03-31  2013-06-23
                 9909     2012-04-02  2013-06-23
                 3203     2012-04-08  2013-06-23
                 9909     2012-04-21  2013-06-23
                          2012-05-06  2013-06-23
                          2012-05-15  2013-06-23
                          2012-05-30  2013-06-23
                          2012-06-02  2013-06-23
                          2012-06-30  2013-06-23
                          2012-07-06  2013-06-23
                          2012-07-11  2013-06-23
                          2012-07-12  2013-06-23
                          2012-07-18  2013-06-23
                          2012-07-23  2013-06-23
                          2012-07-25  2013-06-23
                          2012-07-30  2013-06-23
                          2012-08-01  2013-06-23
                          2012-08-04  2013-06-23
                          2012-08-24  2013-06-23
                          2012-09-11  2013-06-23
                          2012-09-21  2013-06-23
                 3509     2012-09-29  2013-06-23
                 9909     2012-10-11  2013-06-23
                          2012-10-18  2013-06-23
...                                          ...
4813248649 40    3203     2013-06-27  2013-07-24
                 5616     2013-06-28  2013-07-24
                          2013-06-29  2013-07-24
                          2013-06-29  2013-07-24
                 706      2013-06-30  2013-07-24
                 3203     2013-06-30  2013-07-24
                 7205     2013-06-30  2013-07-24
                 5122     2013-06-30  2013-07-24
                 3509     2013-06-30  2013-07-24
                 5616     2013-07-03  2013-07-24
                          2013-07-03  2013-07-24
                 3509     2013-07-07  2013-07-24
                 7205     2013-07-08  2013-07-24
                 5616     2013-07-13  2013-07-24
                 3203     2013-07-13  2013-07-24
                 7205     2013-07-15  2013-07-24
                          2013-07-16  2013-07-24
                 3203     2013-07-18  2013-07-24
                 5616     2013-07-20  2013-07-24
                          2013-07-20  2013-07-24
                          2013-07-20  2013-07-24
                 5122     2013-07-20  2013-07-24
                          2013-07-20  2013-07-24
                 5616     2013-07-21  2013-07-24
                 7205     2013-07-21  2013-07-24
4847628950 166   5616     2013-07-21  2013-07-24
                 7205     2013-07-21  2013-07-24
                 9909     2013-07-22  2013-07-24
                          2013-07-23  2013-07-24
4847787712 46    3509     2013-07-21  2013-07-26

[1066754 rows x 10 columns]

In [12]:
feature_names = ['S_category_180',
'P_amt_category_180',
'S_category_120',
'P_amt_category_120',
'S_category_90',
'P_amt_category_90',
'S_category_60',
'P_amt_category_60',
'S_category_30',
'P_amt_category_30',
'S_company_180',
'P_amt_company_180',
'S_company_120',
'P_amt_company_120',
'S_company_90',
'P_amt_company_90',
'S_company_60',
'P_amt_company_60',
'S_company_30',
'P_amt_company_30',
'S_brand_180',
'P_amt_brand_180',
'S_brand_120',
'P_amt_brand_120',
'S_brand_90',
'P_amt_brand_90',
'S_brand_60',
'P_amt_brand_60',
'S_brand_30',
'P_amt_brand_30',
'S_all_180',
'P_amt_all_180',
'S_all_120',
'P_amt_all_120',
'S_all_90',
'P_amt_all_90',
'S_all_60',
'P_amt_all_60',
'S_all_30',
'P_amt_all_30',
'S_dept_180',
'P_amt_dept_180',
'S_dept_30',
'P_amt_dept_30',
'NE_category_180',                 
'NE_company_180',
'NE_brand_180',
'NE_category_30',                 
'NE_company_30',
'NE_brand_30',
'D_brand_180',
'D_company_180',
'D_category_180',
'D_brand_30',
'D_company_30',
'D_category_30',
'P_amt_diff_brand_30',
'P_amt_diff_brand_180',    
'P_amt_diff_company_30',
'P_amt_diff_company_180',    
'P_amt_diff_category_30',
'P_amt_diff_category_180',
'category_pop',
'company_pop',
'brand_pop',
'offer_value',
'offer_quantity',
'offer_category',
'offer_brand',
'offer_company']


columns = {}
for i in feature_names:
        column_name=i
        columns[column_name]=[]
print columns

{'offer_quantity': [], 'P_amt_brand_90': [], 'P_amt_dept_30': [], 'NE_brand_30': [], 'S_all_120': [], 'company_pop': [], 'S_company_90': [], 'P_amt_diff_category_30': [], 'S_category_90': [], 'S_brand_120': [], 'NE_company_30': [], 'offer_value': [], 'brand_pop': [], 'NE_company_180': [], 'P_amt_category_180': [], 'P_amt_dept_180': [], 'offer_brand': [], 'S_company_180': [], 'P_amt_company_60': [], 'P_amt_category_30': [], 'S_brand_30': [], 'NE_category_180': [], 'P_amt_company_180': [], 'S_all_180': [], 'S_company_30': [], 'P_amt_brand_60': [], 'P_amt_diff_brand_180': [], 'P_amt_brand_180': [], 'S_all_60': [], 'P_amt_diff_company_180': [], 'P_amt_all_60': [], 'P_amt_category_120': [], 'P_amt_category_90': [], 'D_company_180': [], 'S_category_60': [], 'S_dept_180': [], 'offer_category': [], 'P_amt_company_90': [], 'D_category_180': [], 'P_amt_brand_120': [], 'NE_brand_180': [], 'P_amt_all_180': [], 'P_amt_all_120': [], 'P_amt_company_120': [], 'D_brand_180': [], 'S_category_120': [], 'P_amt_all_90': [], 'S_brand_60': [], 'S_all_90': [], 'category_pop': [], 'D_category_30': [], 'NE_category_30': [], 'P_amt_diff_category_180': [], 'S_company_60': [], 'P_amt_diff_company_30': [], 'P_amt_brand_30': [], 'P_amt_diff_brand_30': [], 'S_brand_90': [], 'S_category_180': [], 'P_amt_all_30': [], 'S_dept_30': [], 'P_amt_category_60': [], 'P_amt_company_30': [], 'offer_company': [], 'D_company_30': [], 'S_category_30': [], 'S_brand_180': [], 'S_all_30': [], 'S_company_120': [], 'D_brand_30': []}

In [13]:
t0=time()
train_transaction_category_joined_groupby_id = train_transaction_category_joined.groupby('id')
train_transaction_company_joined_groupby_id = train_transaction_company_joined.groupby('id')
train_transaction_brand_joined_groupby_id = train_transaction_brand_joined.groupby('id')
train_transaction_all_joined_groupby_id = train_transaction_all_joined.groupby('id')
transaction_category_groups = train_transaction_category_joined.groupby('category')
transaction_company_groups = train_transaction_company_joined.groupby('company')
transaction_brand_groups = train_transaction_brand_joined.groupby('brand')
t1=time()

In [14]:
pop_category = {}
pop_company = {}
pop_brand = {}

for name, group in transaction_category_groups:
    pop_category[name] = len(group)
for name, group in transaction_company_groups:
    pop_company[name] = len(group)
for name, group in transaction_brand_groups:
    pop_brand[name] = len(group)

In [15]:
from datetime import datetime
from datetime import timedelta
import numpy as np
import sys
import copy
import os.path

dept = {}
cnt = 0

f = open('log3.txt', 'w')

def noOfPurchaseWithCategory(transactions,category,offerDate,period):
    endDate=datetime.strptime(offerDate,'%Y-%m-%d')
    tmDelta=timedelta(days=period)
    startDate=endDate-tmDelta
    start_date = startDate.strftime('%Y-%m-%d')
    end_date = endDate.strftime('%Y-%m-%d')
    results=transactions[transactions.apply(lambda x: (x.category==category) &(start_date<= x.date) & (x.date<=end_date), axis = 1)]    
    purchasequantity = np.asarray(results['purchasequantity'])
    purchaseamount = np.asarray(results['purchaseamount'])
    product_sum = np.dot(purchasequantity, purchaseamount)

    return results.shape[0], product_sum

def noOfPurchaseWithCompany(transactions,company,offerDate,period):
    endDate=datetime.strptime(offerDate,'%Y-%m-%d')
    tmDelta=timedelta(days=period)
    startDate=endDate-tmDelta
    start_date = startDate.strftime('%Y-%m-%d')
    end_date = endDate.strftime('%Y-%m-%d')
    results=transactions[transactions.apply(lambda x: (x.company==company) &(start_date<= x.date) & (x.date<=end_date), axis = 1)]
    
    purchasequantity = np.asarray(results['purchasequantity'])
    purchaseamount = np.asarray(results['purchaseamount'])
    product_sum = np.dot(purchasequantity, purchaseamount)
    
    return results.shape[0], product_sum

def noOfPurchaseWithBrand(transactions,brand,offerDate,period):
    endDate=datetime.strptime(offerDate,'%Y-%m-%d')
    tmDelta=timedelta(days=period)
    startDate=endDate-tmDelta
    start_date = startDate.strftime('%Y-%m-%d')
    end_date = endDate.strftime('%Y-%m-%d')
    results=transactions[transactions.apply(lambda x: (x.brand==brand) &(start_date<= x.date) & (x.date<=end_date), axis = 1)]

    purchasequantity = np.asarray(results['purchasequantity'])
    purchaseamount = np.asarray(results['purchaseamount'])
    product_sum = np.dot(purchasequantity, purchaseamount)
    
    return results.shape[0], product_sum

def noOfPurchaseWithDept(transactions,category,offerDate,period):
    endDate=datetime.strptime(offerDate,'%Y-%m-%d')
    tmDelta=timedelta(days=period)
    startDate=endDate-tmDelta
    start_date = startDate.strftime('%Y-%m-%d')
    end_date = endDate.strftime('%Y-%m-%d')
    
    if category not in dept:
        department_df = transactions[transactions.apply(lambda x: x.category==category, axis = 1)]
        dept_id = department_df['dept']
        for i in dept_id.index:
            deptid = dept_id[i]
            break
        
        dept[category] = deptid
    else:
        deptid = dept[category]
        

    results=transactions[transactions.apply(lambda x: (start_date<= x.date) & (x.date<=end_date) & (x.dept==deptid), axis = 1)]
    purchasequantity = np.asarray(results['purchasequantity'])
    purchaseamount = np.asarray(results['purchaseamount'])
    product_sum = np.dot(purchasequantity, purchaseamount)

    return results.shape[0], product_sum

def noOfPurchaseWithAll(transactions,category, brand, company,offerDate,period):
    endDate=datetime.strptime(offerDate,'%Y-%m-%d')
    tmDelta=timedelta(days=period)
    startDate=endDate-tmDelta
    start_date = startDate.strftime('%Y-%m-%d')
    end_date = endDate.strftime('%Y-%m-%d')
    results=transactions[transactions.apply(lambda x:(x.category==category) & (x.brand==brand)& (x.company==company) & (start_date<= x.date) & (x.date<=end_date), axis = 1)]
    
    purchasequantity = np.asarray(results['purchasequantity'])
    purchaseamount = np.asarray(results['purchaseamount'])
    product_sum = np.dot(purchasequantity, purchaseamount)
    
    return results.shape[0], product_sum

def noOfPurchaseWithCategoryDiff(transactions,offerDate,period):
    endDate=datetime.strptime(offerDate,'%Y-%m-%d')
    tmDelta=timedelta(days=period)
    startDate=endDate-tmDelta
    start_date = startDate.strftime('%Y-%m-%d')
    end_date = endDate.strftime('%Y-%m-%d')
    
    results=transactions[transactions.apply(lambda x:(start_date<= x.date) & (x.date<=end_date), axis = 1)]
    diff_category = results.groupby('category')
    
    purchasequantity = np.asarray(results['purchasequantity'])
    purchaseamount = np.asarray(results['purchaseamount'])
    product_sum = np.dot(purchasequantity, purchaseamount)
    
    return len(diff_category), product_sum

def noOfPurchaseWithCompanyDiff(transactions,offerDate,period):
    endDate=datetime.strptime(offerDate,'%Y-%m-%d')
    tmDelta=timedelta(days=period)
    startDate=endDate-tmDelta
    start_date = startDate.strftime('%Y-%m-%d')
    end_date = endDate.strftime('%Y-%m-%d')
    
    results=transactions[transactions.apply(lambda x:(start_date<= x.date) & (x.date<=end_date), axis = 1)]
    diff_company = results.groupby('company')

    purchasequantity = np.asarray(results['purchasequantity'])
    purchaseamount = np.asarray(results['purchaseamount'])
    product_sum = np.dot(purchasequantity, purchaseamount)
    
    return len(diff_company), product_sum


def noOfPurchaseWithBrandDiff(transactions,offerDate,period):
    endDate=datetime.strptime(offerDate,'%Y-%m-%d')
    tmDelta=timedelta(days=period)
    startDate=endDate-tmDelta
    start_date = startDate.strftime('%Y-%m-%d')
    end_date = endDate.strftime('%Y-%m-%d')
    
    results=transactions[transactions.apply(lambda x:(start_date<= x.date) & (x.date<=end_date), axis = 1)] 
    diff_brand = results.groupby('brand')

    purchasequantity = np.asarray(results['purchasequantity'])
    purchaseamount = np.asarray(results['purchaseamount'])
    product_sum = np.dot(purchasequantity, purchaseamount)
    
    return len(diff_brand), product_sum

def noOfPurchaseWithCategoryNegative(transactions,category,offerDate,period):
    sys.stdout.flush()
    endDate=datetime.strptime(offerDate,'%Y-%m-%d')
    tmDelta=timedelta(days=period)
    startDate=endDate-tmDelta
    start_date = startDate.strftime('%Y-%m-%d')
    end_date = endDate.strftime('%Y-%m-%d')
    results=transactions[transactions.apply(lambda x:(x.category==category) & (start_date<= x.date) & (x.date<=end_date) & (x.purchaseamount<0.0), axis = 1)]

    return results.shape[0]

def noOfPurchaseWithCompanyNegative(transactions,company,offerDate,period):
    endDate=datetime.strptime(offerDate,'%Y-%m-%d')
    tmDelta=timedelta(days=period)
    startDate=endDate-tmDelta
    start_date = startDate.strftime('%Y-%m-%d')
    end_date = endDate.strftime('%Y-%m-%d')
    results=transactions[transactions.apply(lambda x:(x.company==company) & (start_date<= x.date) & (x.date<=end_date) & (x.purchaseamount<0.0), axis = 1)]

    return results.shape[0]

def noOfPurchaseWithBrandNegative(transactions,brand,offerDate,period):
    endDate=datetime.strptime(offerDate,'%Y-%m-%d')
    tmDelta=timedelta(days=period)
    startDate=endDate-tmDelta
    start_date = startDate.strftime('%Y-%m-%d')
    end_date = endDate.strftime('%Y-%m-%d')
    results=transactions[transactions.apply(lambda x:(x.brand==brand) & (start_date<= x.date) & (x.date<=end_date)& (x.purchaseamount<0.0), axis = 1)]
    
    return results.shape[0]

def noOfPurchaseWithAllNegative(transactions,category, brand, company,offerDate,period):
    endDate=datetime.strptime(offerDate,'%Y-%m-%d')
    tmDelta=timedelta(days=period)
    startDate=endDate-tmDelta
    start_date = startDate.strftime('%Y-%m-%d')
    end_date = endDate.strftime('%Y-%m-%d')
    results=transactions[transactions.apply(lambda x: (x.category==category) & (x.brand==brand)& (x.company==company)  & (start_date<= x.date) & (x.date<=end_date) & (x.purchaseamount<0.0), axis = 1)]

    return results.shape[0]

def findPopularity(transactions, offerDate,period):
    endDate=datetime.strptime(offerDate,'%Y-%m-%d')
    tmDelta=timedelta(days=period)
    startDate=endDate-tmDelta
    start_date = startDate.strftime('%Y-%m-%d')
    end_date = endDate.strftime('%Y-%m-%d')
    results=transactions[transactions.apply(lambda x: (start_date<= x.date) & (x.date<=end_date), axis = 1)]
    return results.shape[0]
    
train_category = offer_train['category']
train_company = offer_train['company']
train_brand = offer_train['brand']
train_id = offer_train['id']
train_date = offer_train['offerdate']
train_offer_value = offer_train['offervalue']
train_offer_quantity = offer_train['quantity']

train_file_name = 'test_features_final.csv'

rows=len(train_date)
start = 0
end = 151484
rows_read=0
exists = os.path.exists(train_file_name)
if exists == True:
    file_dataframe = pd.read_csv(train_file_name)
    rows_read = len(file_dataframe)
    
row_cnt = 50

columns_temp = copy.deepcopy(columns)

print rows_read

for i in range(start+rows_read, end):
    t0=time()
    
    try:
        transaction_category = train_transaction_category_joined_groupby_id.get_group(train_id[i])
        S_category_180, P_amt_category_180 = noOfPurchaseWithCategory(transaction_category,train_category[i],train_date[i],180)
        S_category_120, P_amt_category_120 = noOfPurchaseWithCategory(transaction_category,train_category[i],train_date[i],120)
        S_category_90, P_amt_category_90 = noOfPurchaseWithCategory(transaction_category,train_category[i],train_date[i],90)
        S_category_60, P_amt_category_60 = noOfPurchaseWithCategory(transaction_category,train_category[i],train_date[i],60)
        S_category_30, P_amt_category_30 = noOfPurchaseWithCategory(transaction_category,train_category[i],train_date[i],30)
        D_Category_180, P_amt_diff_category_180 = noOfPurchaseWithCategoryDiff(transaction_category,train_date[i],180)
        D_Category_30, P_amt_diff_category_30 = noOfPurchaseWithCategoryDiff(transaction_category,train_date[i],30)
        S_dept_180, P_amt_dept_180 = noOfPurchaseWithDept(transaction_category,train_category[i],train_date[i],180)
        S_dept_30, P_amt_dept_30 = noOfPurchaseWithDept(transaction_category,train_category[i],train_date[i],30)
        NE_category_180 = noOfPurchaseWithCategoryNegative(transaction_category,train_category[i],train_date[i],180)
        NE_category_30 = noOfPurchaseWithCategoryNegative(transaction_category,train_category[i],train_date[i],30)
    except:
        S_category_180 = 0
        P_amt_category_180 = 0
        S_category_120 = 0
        P_amt_category_120 = 0
        S_category_90 = 0
        P_amt_category_90 = 0
        S_category_60 = 0
        P_amt_category_60 = 0
        S_category_30 = 0
        P_amt_category_30 = 0
        D_Category_180 = 0
        D_Category_30 = 0
        S_dept_180 = 0
        P_amt_dept_180 = 0
        S_dept_30 = 0
        P_amt_dept_30 = 0
        NE_category_180 = 0
        NE_category_30 = 0
        P_amt_diff_category_180 = 0
        P_amt_diff_category_30 = 0
        
    columns_temp['S_category_180'].append(S_category_180)
    columns_temp['P_amt_category_180'].append(P_amt_category_180)
    columns_temp['S_category_120'].append(S_category_120)
    columns_temp['P_amt_category_120'].append(P_amt_category_120)
    columns_temp['S_category_90'].append(S_category_90)
    columns_temp['P_amt_category_90'].append(P_amt_category_90)
    columns_temp['S_category_60'].append(S_category_60)
    columns_temp['P_amt_category_60'].append(P_amt_category_60)
    columns_temp['S_category_30'].append(S_category_30)
    columns_temp['P_amt_category_30'].append(P_amt_category_30)
    columns_temp['S_dept_30'].append(S_dept_30)
    columns_temp['P_amt_dept_30'].append(P_amt_dept_30)
    columns_temp['S_dept_180'].append(S_dept_180)
    columns_temp['P_amt_dept_180'].append(P_amt_dept_180)
    columns_temp['D_category_30'].append(D_Category_30)
    columns_temp['D_category_180'].append(D_Category_180)
    columns_temp['P_amt_diff_category_30'].append(P_amt_diff_category_30)
    columns_temp['P_amt_diff_category_180'].append(P_amt_diff_category_180)
    columns_temp['NE_category_30'].append(NE_category_30)
    columns_temp['NE_category_180'].append(NE_category_180)
    
    try:
        transaction_company = train_transaction_company_joined_groupby_id.get_group(train_id[i])
        S_company_180, P_amt_company_180 = noOfPurchaseWithCompany(transaction_company,train_company[i],train_date[i],180)
        S_company_120, P_amt_company_120 = noOfPurchaseWithCompany(transaction_company,train_company[i],train_date[i],120)
        S_company_90, P_amt_company_90 = noOfPurchaseWithCompany(transaction_company,train_company[i],train_date[i],90)
        S_company_60, P_amt_company_60 = noOfPurchaseWithCompany(transaction_company,train_company[i],train_date[i],60)
        S_company_30, P_amt_company_30 = noOfPurchaseWithCompany(transaction_company,train_company[i],train_date[i],30)
        NE_company_180 = noOfPurchaseWithCompanyNegative(transaction_company,train_company[i],train_date[i],180)
        NE_company_30 = noOfPurchaseWithCompanyNegative(transaction_company,train_company[i],train_date[i],30)
        D_company_180, P_amt_diff_company_180 = noOfPurchaseWithCompanyDiff(transaction_company,train_date[i],180)
        D_company_30, P_amt_diff_company_30 = noOfPurchaseWithCompanyDiff(transaction_company,train_date[i],30)
    except:
        S_company_180 = 0
        P_amt_company_180 = 0
        S_company_120 = 0
        P_amt_company_120 = 0
        S_company_90 = 0
        P_amt_company_90 = 0
        S_company_60 = 0
        P_amt_company_60 = 0
        S_company_30 = 0
        P_amt_company_30 = 0
        NE_company_180 = 0
        NE_company_30 = 0
        D_company_180 = 0
        D_company_30 = 0
        P_amt_diff_company_180 = 0
        P_amt_diff_company_30 = 0
        
    columns_temp['S_company_180'].append(S_company_180)
    columns_temp['P_amt_company_180'].append(P_amt_company_180)
    columns_temp['S_company_120'].append(S_company_120)
    columns_temp['P_amt_company_120'].append(P_amt_company_120)
    columns_temp['S_company_90'].append(S_company_90)
    columns_temp['P_amt_company_90'].append(P_amt_company_90)
    columns_temp['S_company_60'].append(S_company_60)
    columns_temp['P_amt_company_60'].append(P_amt_company_60)
    columns_temp['S_company_30'].append(S_company_30)
    columns_temp['P_amt_company_30'].append(P_amt_company_30)
    columns_temp['D_company_30'].append(D_company_30)
    columns_temp['D_company_180'].append(D_company_180)
    columns_temp['P_amt_diff_company_30'].append(P_amt_diff_company_30)
    columns_temp['P_amt_diff_company_180'].append(P_amt_diff_company_180)
    columns_temp['NE_company_30'].append(NE_company_30)
    columns_temp['NE_company_180'].append(NE_company_180)

    try:
        transaction_brand = train_transaction_brand_joined_groupby_id.get_group(train_id[i])
        S_brand_30,  P_amt_brand_30 = noOfPurchaseWithBrand(transaction_brand,train_brand[i],train_date[i],30)
        S_brand_120,  P_amt_brand_120 = noOfPurchaseWithBrand(transaction_brand,train_brand[i],train_date[i],120)
        S_brand_90,  P_amt_brand_90 = noOfPurchaseWithBrand(transaction_brand,train_brand[i],train_date[i],90)
        S_brand_60,  P_amt_brand_60 = noOfPurchaseWithBrand(transaction_brand,train_brand[i],train_date[i],60)
        S_brand_180,  P_amt_brand_180 = noOfPurchaseWithBrand(transaction_brand,train_brand[i],train_date[i],180)
        NE_brand_180 = noOfPurchaseWithBrandNegative(transaction_brand,train_brand[i],train_date[i],180)
        NE_brand_30 = noOfPurchaseWithBrandNegative(transaction_brand,train_brand[i],train_date[i],30)
        D_brand_180, P_amt_diff_brand_180 = noOfPurchaseWithBrandDiff(transaction_brand,train_date[i],180)
        D_brand_30, P_amt_diff_brand_30 = noOfPurchaseWithBrandDiff(transaction_brand,train_date[i],30)
    except:
        S_brand_30 = 0
        P_amt_brand_30 = 0
        S_brand_180 = 0
        P_amt_brand_180 = 0
        S_brand_120 = 0
        P_amt_brand_120 = 0
        S_brand_90 = 0
        P_amt_brand_90 = 0
        S_brand_60 = 0
        P_amt_brand_60 = 0
        NE_brand_180 = 0
        NE_brand_30 = 0
        D_brand_180 = 0
        D_brand_30 = 0
        P_amt_diff_brand_30 = 0
        P_amt_diff_brand_180 = 0
        
    columns_temp['S_brand_180'].append(S_brand_180)
    columns_temp['P_amt_brand_180'].append(P_amt_brand_180)
    columns_temp['S_brand_30'].append(S_brand_30)
    columns_temp['P_amt_brand_30'].append(P_amt_brand_30)
    columns_temp['S_brand_60'].append(S_brand_60)
    columns_temp['P_amt_brand_60'].append(P_amt_brand_60)
    columns_temp['S_brand_90'].append(S_brand_90)
    columns_temp['P_amt_brand_90'].append(P_amt_brand_90)
    columns_temp['S_brand_120'].append(S_brand_120)
    columns_temp['P_amt_brand_120'].append(P_amt_brand_120)
    columns_temp['D_brand_30'].append(D_brand_30)
    columns_temp['D_brand_180'].append(D_brand_180)
    columns_temp['P_amt_diff_brand_30'].append(P_amt_diff_brand_30)
    columns_temp['P_amt_diff_brand_180'].append(P_amt_diff_brand_180)
    columns_temp['NE_brand_30'].append(NE_brand_30)
    columns_temp['NE_brand_180'].append(NE_brand_180)
    
    try:
        transaction_all3 = train_transaction_all_joined_groupby_id.get_group(train_id[i])
        S_all_180, P_amt_all_180 = noOfPurchaseWithAll(transaction_all3, train_category[i], train_brand[i], train_company[i],train_date[i],180)
        S_all_120, P_amt_all_120 = noOfPurchaseWithAll(transaction_all3, train_category[i], train_brand[i], train_company[i],train_date[i],120)
        S_all_90, P_amt_all_90 = noOfPurchaseWithAll(transaction_all3, train_category[i], train_brand[i], train_company[i],train_date[i],90)
        S_all_60, P_amt_all_60 = noOfPurchaseWithAll(transaction_all3, train_category[i], train_brand[i], train_company[i],train_date[i],60)
        S_all_30, P_amt_all_30 = noOfPurchaseWithAll(transaction_all3, train_category[i], train_brand[i], train_company[i],train_date[i],30)
       
    except:
        S_all_180 = 0
        P_amt_all_180 = 0
        S_all_120 = 0
        P_amt_all_120 = 0
        S_all_90 = 0
        P_amt_all_90 = 0
        S_all_60 = 0
        P_amt_all_60 = 0
        S_all_30 = 0
        P_amt_all_30 = 0
        
    columns_temp['S_all_180'].append(S_all_180)
    columns_temp['P_amt_all_180'].append(P_amt_all_180)     
    columns_temp['S_all_120'].append(S_all_120)
    columns_temp['P_amt_all_120'].append(P_amt_all_120)   
    columns_temp['S_all_90'].append(S_all_90)
    columns_temp['P_amt_all_90'].append(P_amt_all_90)   
    columns_temp['S_all_60'].append(S_all_60)
    columns_temp['P_amt_all_60'].append(P_amt_all_60)   
    columns_temp['S_all_30'].append(S_all_30)
    columns_temp['P_amt_all_30'].append(P_amt_all_30)  
    columns_temp['offer_value'].append(train_offer_value[i])
    columns_temp['offer_quantity'].append(train_offer_quantity[i])
    columns_temp['offer_brand'].append(train_brand[i])
    columns_temp['offer_category'].append(train_category[i])
    columns_temp['offer_company'].append(train_company[i])
    

    category_pop = pop_category[train_category[i]]
    company_pop = pop_company[train_company[i]]
    brand_pop = pop_brand[train_brand[i]]
    #category_pop_30 = findPopularity(transaction_category_group, train_date[i],30)
    #category_pop_180 = findPopularity(transaction_category_group, train_date[i],180)
    #company_pop_30 = findPopularity(transaction_company_group, train_date[i],30)
    #company_pop_180 = findPopularity(transaction_company_group, train_date[i],180)
    #brand_pop_30 = findPopularity(transaction_brand_group, train_date[i],30)
    #brand_pop_180 = findPopularity(transaction_brand_group, train_date[i],180)
    #columns_temp['category_pop_30'].append(category_pop_30)
    #columns_temp['category_pop_180'].append(category_pop_180)
    #columns_temp['company_pop_30'].append(company_pop_30)
    #columns_temp['company_pop_180'].append(company_pop_180)
    #columns_temp['brand_pop_30'].append(brand_pop_30)
    #columns_temp['brand_pop_180'].append(brand_pop_180)
    columns_temp['category_pop'].append(category_pop)
    columns_temp['company_pop'].append(company_pop)
    columns_temp['brand_pop'].append(brand_pop)
        
    print 'row_read:'+str(i)
    t1=time()
    print 'total time='+str(t1-t0)
    sys.stdout.flush()
    
    if (((i%row_cnt)==0) or (i == end-1)):
        df = pd.DataFrame(columns_temp)
        exists = os.path.exists(train_file_name)
        if exists == True:
            with open(train_file_name, 'a') as f:
                df.to_csv(f, header=False)
        else:
            df.to_csv(train_file_name, header=True)
        columns_temp = copy.deepcopy(columns)
            
#We need to call the above functions with the corresponding transaction value( depending on separate csv files)

151484